![Curso Schwarz-Sosa-Suriano](http://www.fi.uba.ar/sites/default/files/logo.png)
# Sistemas de Ecuaciones Lineales
## Métodos Directos - Refinamiento Iterativo
***
**Curso Schwarz - Sosa - Suriano**
- Métodos Numéricos. *Curso 2*
- Análisis Numérico I. *Curso 4*
- Métodos Matemáticos y Numéricos. *Curso 6*

In [1]:
from IPython.display import display, Math

def factorizarDoolittle(A,pasos=True):
    n = np.shape(A)[0]
    L = np.zeros((n,n))
    U = np.zeros((n,n))
    for i in range (0,n):
        L[i,i] = 1
        U[i,i] = A[i,i]  
        if (pasos):
            display(Math("\\text{Vamos a calcular la "+str(i+1)+"ª fila de U y la "+str(i+1)+"ª columna de L}"))
            display(Math("\\text{Por definición } L_{"+str(i+1)+","+str(i+1)+"} = 1"))                      
            display(Math("\\text{Y para U:}"))    
            exp = "U_{"+str(i+1)+","+str(i+1)+"} = A_{"+str(i+1)+","+str(i+1)+"}"
            expN = "U_{"+str(i+1)+","+str(i+1)+"} = "+str(A[i,i])        
        for k in range(0,i):
            U[i,i] -= L[i,k]*U[k,i] 
            if (pasos):
                exp += " - L_{"+str(i+1)+","+str(k+1)+"} \cdot U_{"+str(k+1)+","+str(i+1)+"}"
                expN += " - "+str(L[i,k])+"\cdot"+str(U[k,i])
        if (pasos):
            expN += "="+str(U[i,i])            
            if (i>2):
                display(Math(exp))
                display(Math(expN))
            else:
                display(Math(exp+"\\implies "+expN))
            display(Math("\\text{Seguimos con la "+str(i+1)+"ª fila de U y la "+str(i+1)+"ª columna de L }"))            
        for j in range (i+1,n):         
            U[i,j] = A[i,j]             
            L[j,i] = A[j,i]
            if (pasos):
                exp1 = "U_{"+str(i+1)+","+str(j+1)+"} = \\frac{A_{"+str(i+1)+","+str(j+1)+"}"  
                exp1N = "U_{"+str(i+1)+","+str(j+1)+"} = \\frac{"+str(A[i,j])
                exp2 = "L_{"+str(j+1)+","+str(i+1)+"} = \\frac{A_{"+str(j+1)+","+str(i+1)+"}" 
                exp2N = "L_{"+str(j+1)+","+str(i+1)+"} = \\frac{"+str(A[j,i])                
            for k in range(0,i):           
                U[i,j] -= L[i,k]*U[k,j]                  
                L[j,i] -= L[j,k]*U[k,i] 
                if (pasos):
                    exp1  += " - L_{"+str(i+1)+","+str(k+1)+"} \cdot U_{"+str(k+1)+","+str(j+1)+"}"  
                    exp1N += " - "+str(L[i,k])+" \cdot "+str(U[k,j])                     
                    exp2  += " - L_{"+str(j+1)+","+str(k+1)+"} \cdot U_{"+str(k+1)+","+str(i+1)+"}" 
                    exp2N += " - "+str(L[j,k])+" \cdot "+str(U[k,i])                     
            U[i,j] = U[i,j]/L[i,i] 
            L[j,i] = L[j,i]/U[i,i]
            if (pasos):
                exp1  += "}{L_{"+str(i+1)+","+str(i+1)+"}}"   
                exp1N += "}{1} = "+str(U[i,j])               
                exp2  += "}{U_{"+str(i+1)+","+str(i+1)+"}}"  
                exp2N += "}{"+str(U[i,i])+"} = "+str(L[j,i])             
                if (i>2):
                    display(Math(exp1))
                    display(Math(exp1N))                
                    display(Math(exp2)) 
                    display(Math(exp2N))   
                else:
                    display(Math(exp1+"\\implies "+exp1N))
                    display(Math(exp2+"\\implies "+exp2N))
        if (pasos):
            if (i<n-1):
                display(Math("\\text{Y hasta acá tenemos:}"))                
            else:
                display(Math("\\text{Y ahora sí tenemos L y U completas:}"))
            display(Math("L = "+bmatrix(L)+" \\hspace{10mm} U = "+bmatrix(U)+" \\hspace{10mm} A = "+bmatrix(A)))
    return L,U 

def bmatrix(a):
    # credito: https://stackoverflow.com/questions/17129290/numpy-2d-and-1d-array-to-latex-bmatrix
    if len(a.shape) > 2:
        raise ValueError('solo vectores o matrices bidimensionales')
    lines = str(a).replace('[', '').replace(']', '').splitlines()
    rv = [r'\begin{bmatrix}']
    rv += ['  ' + ' & '.join(l.split()) + r'\\' for l in lines]
    rv +=  [r'\end{bmatrix}']
    return '\n'.join(rv)

def sustDirecta(L, B, pasos = True):
    n = np.shape(L)[0]
    Y = np.zeros(n)    
    if (pasos):
        display(Math("\\text{Tenemos:}"))                
        exp = bmatrix(L)+" \cdot \\begin{bmatrix}"
        for i in range(0,n): exp += "Y_"+str(i+1)+r"\\"       
        exp += "\\end{bmatrix} = "+bmatrix(B.reshape(-1,1))
        display(Math(exp))
    for i in range(0,n):
        Y[i] = B[i]
        if (pasos):       
            if (i+1==n): 
                display(Math("\\text{Y por último calculamos } Y_"+str(i+1)))             
            elif (i==0):
                display(Math("\\text{Primero calculamos } Y_"+str(i+1)))                                  
            else:
                display(Math("\\text{Ahora calculamos } Y_"+str(i+1)))                    
            exp = "Y_"+str(i+1)+" = \\frac{B_"+str(i+1)
            expN = "Y_"+str(i+1)+" = \\frac{" + str(B[i])           
        for j in range (0,i):
            Y[i] += -L[i,j]*Y[j]
            if (pasos):
                exp  += " - L_{"+str(i+1)+","+str(j+1)+"} \cdot Y_"+str(j+1) 
                expN += " - "+str(L[i,j])+" \cdot "+str(Y[j])            
        Y[i] = Y[i] / L[i,i]
        if (pasos):
            exp += "}{L_{"+str(i+1)+","+str(i+1)+"}}"
            expN += "}{1} = "+str([i])
            display(Math(exp))
            display(Math(expN))
    if (pasos):
        display(Math("\\text{Y finalmente:}"))                
        display(Math("Y = "+bmatrix(Y)))               
    return Y

def sustInversa(U, Y ,pasos = True):
    n = np.shape(U)[0]
    X = np.zeros(n)
    if (pasos):
        display(Math("\\text{Tenemos:}"))                
        exp = bmatrix(U)+" \cdot \\begin{bmatrix}"
        for i in range(0,n): exp += "X_"+str(i+1)+r"\\"       
        exp += "\\end{bmatrix} = "+bmatrix(Y.reshape(-1,1))
        display(Math(exp))  
    for i in reversed(range(0,n)):
        X[i] = Y[i]        
        if (pasos):       
            if (i+1==n): 
                display(Math("\\text{Primero calculamos } X_"+str(i+1)))           
            elif (i==0):
                display(Math("\\text{Y por último calculamos } X_"+str(i+1)))                    
            else:
                display(Math("\\text{Ahora calculamos } X_"+str(i+1)))                    
            exp = "X_"+str(i+1)+" = \\frac{Y_"+str(i+1)
            expN = "X_"+str(i+1)+" = \\frac{" + str(Y[i])               
        for j in range (i+1,n):
            X[i] += -U[i,j]*X[j]
            if (pasos):
                exp  += " - U_{"+str(i+1)+","+str(j+1)+"} \cdot X_"+str(j+1) 
                expN += " - "+str(U[i,j])+" \cdot "+str(X[j])
        X[i] = X[i] / U[i,i]  
        if (pasos):
            exp += "}{U_{"+str(i+1)+","+str(i+1)+"}}"
            expN += "}{"+str(U[i,i])+"} = "+str(X[i])
            display(Math(exp))
            display(Math(expN))    
    if (pasos):
        display(Math("\\text{Y finalmente:}"))                
        display(Math("X = "+bmatrix(X)))   
    return X

def factorizarCholesky(A,pasos=True):
    n = np.shape(A)[0]
    S = np.zeros((n,n))
    for i in range (0,n):
        S[i,i] = A[i,i]  
        if (pasos):
            display(Math("\\text{Vamos a calcular la "+str(i+1)+"ª  columna de S}"))
            exp = "S_{"+str(i+1)+","+str(i+1)+"} = \sqrt{ A_{"+str(i+1)+","+str(i+1)+"}"
            expN = "S_{"+str(i+1)+","+str(i+1)+"} = \sqrt{"+str(A[i,i])        
        for k in range(0,i):
            S[i,i] += - S[i,k]**2
            if (pasos):
                exp += " - S_{"+str(i+1)+","+str(k+1)+"}^2"
                expN += " - "+str(S[i,k])+"^2"
        S[i,i] = np.sqrt(S[i,i])
        if (pasos):
            exp += "}"            
            expN += "} ="+str(S[i,i])            
            if (i>2):
                display(Math(exp))
                display(Math(expN))
            else:
                display(Math(exp+"\\implies "+expN))       
        for j in range (i+1,n):     
            S[j,i] = A[j,i]
            if (pasos):
                exp = "S_{"+str(j+1)+","+str(i+1)+"} = \\frac{A_{"+str(j+1)+","+str(i+1)+"}" 
                expN = "S_{"+str(j+1)+","+str(i+1)+"} = \\frac{"+str(A[j,i])                
            for k in range(0,i):           
                S[j,i] += - S[j,k]*S[i,k]                  
                if (pasos):
                    exp  += " - S_{"+str(j+1)+","+str(k+1)+"} \cdot S_{"+str(i+1)+","+str(k+1)+"}"  
                    expN += " - "+str(S[j,k])+" \cdot "+ str(S[i,k])                  
            S[j,i] = S[j,i] / S[i,i]
            if (pasos):            
                exp  += "}{S_{"+str(i+1)+","+str(i+1)+"}}"  
                expN += "}{"+str(S[i,i])+"} = "+str(S[j,i])              
                if (i>2):
                    display(Math(exp))
                    display(Math(expN))                
                else:
                    display(Math(exp+"\\implies "+expN))
        if (pasos):
            if (i<n-1):
                display(Math("\\text{Y hasta acá tenemos:}"))                
            else:
                display(Math("\\text{Y ahora sí tenemos S completa:}"))
            display(Math("S = "+bmatrix(S)+" \\hspace{10mm} A = "+bmatrix(A)))
    return S

### Matrices mal condicionadas:

En el Resumen de Clases Teórias han visto ya el tema de las Condición de una Matriz. Sabemos que: 

$$ \kappa(A) = ||A|| \cdot ||A^{-1}|| $$

Se pude decir que $\kappa (A)$ es una medida de qué tan cerca está una matriz de tener un determinante nulo. A mayor valor de $\kappa(A)$ menor será el valor de $det(A)$.

Generemos una matriz mal condicionada:

In [2]:
import numpy as np
A = np.matrix([[5000,  1, 5], [ 1, 10000,  1], [ 5001,  10001,  5.99999999999999]])
print(A)
print(np.linalg.det(A))

[[5.0000e+03 1.0000e+00 5.0000e+00]
 [1.0000e+00 1.0000e+04 1.0000e+00]
 [5.0010e+03 1.0001e+04 6.0000e+00]]
-5.051647861134412e-07


Aplicaremos la factorización de Doolittle, proponiendo primero un vector B:

In [11]:
B = np.array([100,100,100])
L, U = factorizarDoolittle(A,False)
Y0 = sustDirecta(L, B, False)
X0 = sustInversa(U, Y0, False)
print (X0)

[-1.08518305e+13 -1.08411955e+12  1.08520473e+16]


Calculemos el residuo $R$ y una medida del error de la solución en términos relativos de $B$: $\frac{||R||}{||B||}$

In [4]:
R0 = B - np.dot(A,X0)
rel0 = np.linalg.norm(R0.transpose(),np.inf)/np.linalg.norm(B.transpose(),np.inf)
print(R0,rel0)

[[12.  2. 20.]] 0.2


Si la solución fuera la exacta deberíamos haber tenido como residuo el vector nulo, pero cuando tenemos matrices mal condicionadas, este tipo de situaciones pueden ocurrir.

En estos casos, podemos reutilizar los resultados de la factorización para en el denominado refinamiento iterativo.

### Refinamiento iterativo de la solución:

Sabemos que esta **estrategia iterativa** permite aprovechar el trabajo realizado con un **método directo** para hallar la solución (que ahora llamaremos $X_0$, para diferenciarla de la solución exacta $X$) de la siguiente forma:

$$R_0 = B - A \cdot X_0$$

$$B = A \cdot X \implies R_0 = A \cdot X - A \cdot X_0$$

$$R_0 = A \cdot (X-X_0)$$


$$A \cdot \delta_0 = R_0 \hspace{5mm} con \hspace{5mm} X = X_0 + \delta_0$$

En consecuencia, si resolvemos el nuevo sel $A \cdot \delta_0 = R_0$ y sumamos $\delta_0$ a la primer solución $X_0$, deberíamos obtener *-al menos una solución más próxima a-* la solución exacta:

In [12]:
Y1 = sustDirecta(L, R0.transpose(),False)
delta0 = sustInversa(U, Y1, False)
X1 = X0 + delta0

Calculamos ahora el nuevo residuo $R$ y la relación $\frac{||R||}{||B||}$:

In [8]:
R1 = B - np.dot(A,X1)
rel1 = np.linalg.norm(R1.transpose(),np.inf)/np.linalg.norm(B.transpose(),np.inf)
print(R1, rel1)
print (rel1,"y antes esta misma relación era al hallar X0",rel0)

[[ 4. -2. -4.]] 0.04
0.04 y antes esta misma relación era al hallar X0 0.2


Como vemos, el refinamiento ha mejorado el resultado obtenido. Podríamos repetir el proceso tantas veces como queramos, implementando criterios de corte similares a los que veremos en el próximo video de **Métodos Iterativos**.

A modo de cierre, vamos a utilizar la función numpy que propone calcular el número de condición de una matriz basado en la norma infinito, y compararlo con la estimación (3.31) del Resumen de Clases, recordando que en nuestro caso tenemos $t=15$:
$$\kappa(A) \approx \frac{||\delta_0||}{||X_0||}\cdot 10^t$$

In [13]:
Kestimado = (np.linalg.norm(delta0.transpose(),np.inf)/np.linalg.norm(X0.transpose(),np.inf))*(10**15)
Knumpy = np.linalg.cond(A,np.inf)
print (Kestimado, Knumpy)
print ("Relación Numpy/Estimado:",Knumpy/Kestimado)

59999999999999.99 4.456367539582331e+18
Relación Numpy/Estimado: 74272.79232637219


A pesar de que el valor estimado es mucho menor al estimado numéricamente por Numpy, la sola estimación nos da una idea de que tenemos un $\kappa(A)$ elevado, sin necesidad de tener que calcular la inversa de la matriz como hace Numpy *- a pesar que en este caso no se note el consumo de recursos por el tamaño reducido de la matriz-.*