![Curso Schwarz-Sosa-Suriano](http://www.fi.uba.ar/sites/default/files/logo.png)
# Sistemas de Ecuaciones Lineales
## Métodos Iterativos no Estacionarios
***
**Curso Schwarz - Sosa - Suriano**
- Métodos Numéricos. *Curso 2*
- Análisis Numérico I. *Curso 4*
- Métodos Matemáticos y Numéricos. *Curso 6*

### Métodos iterativos no estacionarios:

Los métodos iterativos no estacionarios se presentan como una alternativa eficiente para resolver SEL con matrices ralas. Sabemos que todos los métodos iterativos vistos hasta aquí pueden representarse con la expresión:

$$X^{(k+1)} = T \cdot X^{(k)} +C$$

Esta fórmula también representa a los métodos iterativos no estacionarios, ya que obtienen su denominación del hecho de que la matriz T y el vector C no son constantes -o estacionarios- como sí lo son en los métodos de Jacobi, Gauss Seidel y SOR. No obstante, hay una expresión que nos interesa un poco más, ya que define la mecánica iterativa de casi todos ellos:

$$X^{(k+1)} = X^{(k)} + \alpha_k \cdot R^{(k)}$$

Donde $\alpha$ es un parámetro que varía con cada iteración **y cuya expresión se obtiene de forma distinta para cada uno de los Métodos**. A partir de esta expresión, el resíduo de la iteración siguiente puede reformularse como:

$$R^{(k+1)} = B - A \cdot X^{(k+1)} = B - A \cdot ( X^{(k)} + \alpha_k \cdot R^{(k)}) =  B - A \cdot X^{(k)} - \alpha_k \cdot A \cdot R^{(k)} \implies R^{(k+1)} = R^{(k)} - \alpha_k \cdot A \cdot R^{(k)}$$

### Metodo de los Mínimos Residuos:

Este método propone la minimización del resíduo como un camino para buscar la mejor aproximación de $X$. Para ello se deriva el residuo respecto del parámetro $\alpha$ y se iguala a cero su expresión para despejar el siguiente valor:

$$ \alpha_k = \dfrac{(A\cdot R^{(k)})^T \cdot R^{(k)}}{(A\cdot R^{(k)})^T \cdot A \cdot R^{(k)}} $$

Este método converge si A es definida positiva, y el algoritmo adopta la forma:

$$R^{(0)} = B - A \cdot X^{(0)} \hspace{5mm} \text{solo en la primera iteración}$$

$$ \alpha_k = \dfrac{(A\cdot R^{(k)})^T \cdot R^{(k)}}{(A\cdot R^{(k)})^T \cdot A \cdot R^{(k)}} $$

$$X^{(k+1)} = X^{(k)} + \alpha_k \cdot R^{(k)}$$

$$R^{(k+1)} = R^{(k)} - \alpha_k \cdot A \cdot R^{(k)}$$

### Problema a resolver:

In [1]:
from IPython.display import display, Math
import numpy as np
A = np.matrix([[10,-1,2,0],[-1,11,-1,3],[2,-1,10,5],[0,3,5,20]])
print(A)
B = np.array([6,25,-11,15])

[[10 -1  2  0]
 [-1 11 -1  3]
 [ 2 -1 10  5]
 [ 0  3  5 20]]


En el bloque de código encontrarán una función `resolverMMR(A,B,tol,pasos)` que permite resolver un SEL a partir de conocer la matriz $ A $ y el vector $ B $, fijar una tolerancia `tol` e indicar con `True` o `False` si queremos o no que se acompañe la resolución con el procedimiento paso a paso. 

Y si quieren obtener un código más limpio, sin ninguna referencia de paso a paso, pueden eliminar cada uno de los bloques que comienzan con `if (pasos):`

In [2]:
def resolverMMR(A, B, tol, pasos=True):
    n = np.shape(A)[0]
    X1 = np.zeros(n)
    R1 = np.copy(B)
    den = np.linalg.norm(B,np.inf)
    if (den==0): den = 1    
    iteracion = 0
    dif = 2*tol
    while (dif>tol):
        if (pasos):
            display(Math("\\text{Vamos a realizar la "+str(iteracion+1)+"ª iteración}")) 
            if (iteracion==0):
                display(Math("\\text{Adoptamos como vector inicial } X^{(0)} = "+r"\begin{bmatrix} 0 \\ 0 \\ ... \\ 0 \end{bmatrix}"))            
                display(Math("\\text{En consecuencia } R^{(0)} = B"))    
        X0 = np.copy(X1) 
        R0 = np.copy(R1).reshape(-1)
        AR0 = np.dot(A,R0)        
        alfa = (np.inner(AR0,R0) / np.inner(AR0,AR0)).item()
        X1 = X0 + alfa*R0       
        R1 = R0 - alfa*AR0    
        dif = np.linalg.norm(R1.transpose(),np.inf)/den        
        if (pasos):
            display(Math("A \\cdot R^{("+str(iteracion)+")} = "+bmatrix(AR0)+"^T"))   
            exp = r"\alpha_"+str(iteracion)+" = \dfrac{(A\cdot R^{("+str(iteracion)+")})^T \cdot R^{("+str(iteracion)+")}}{(A\cdot R^{("+str(iteracion)+")})^T \cdot A \cdot R^{("+str(iteracion)+")}} =" +str(alfa)
            display(Math(exp)) 
            exp = "X^{("+str(iteracion+1)+")} = X^{("+str(iteracion)+r")} + \alpha_{"+str(iteracion)+"} \cdot R^{("+str(iteracion)+")} = "+bmatrix(X1)
            display(Math(exp))
            exp = "R^{("+str(iteracion+1)+")} = R^{("+str(iteracion)+r")} - \alpha_{"+str(iteracion)+r"} \cdot A \cdot R^{("+str(iteracion)+")} = "+bmatrix(R1)
            display(Math(exp)) 
            exp = "\\text{Evaluamos el criterio corte: } \\frac{|| R^{("+str(iteracion+1)+")}||}{|| B ||} = "+str(dif)            
            if (dif>tol):
                exp += " > tol = "+str(tol)
                display(Math(exp)) 
            else:
                exp +=  " \leq tol = "+str(tol)
                display(Math(exp)) 
                exp = "\\text{Y hemos encontrado nuestra solución aproximada: } X^{("+str(iteracion+1)+")} = "+bmatrix(X1)
                display(Math(exp))
        iteracion += 1                
    return (X1)

def bmatrix(a):
    # credito: https://stackoverflow.com/questions/17129290/numpy-2d-and-1d-array-to-latex-bmatrix
    if len(a.shape) > 2:
        raise ValueError('solo vectores o matrices bidimensionales')
    lines = str(a).replace('[', '').replace(']', '').splitlines()
    rv = [r'\begin{bmatrix}']
    rv += ['  ' + ' & '.join(l.split()) + r'\\' for l in lines]
    rv +=  [r'\end{bmatrix}']
    return '\n'.join(rv)

In [3]:
resolverMMR(A,B,10**-4,True)

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

array([ 1.10802655,  2.00649807, -1.53741104,  0.83326644])

### Metodo del Descenso Más Rápido:

Este método interpreta la solución de nuestro SEL como el mínimo de una Forma Cuadrática (equivalente a una función cuadrática pero en $\mathbb{R}^n$) y propone como dirección para la búsqueda de ese mínimo la de los residuos de cada iteración, que resultan opuestos al gradiente. De allí, se obtiene:

$$ \alpha_k = \dfrac{(R^{(k)})^T \cdot R^{(k)}}{(R^{(k)})^T \cdot A \cdot R^{(k)}} $$

Este método converge si A es simétrica definida positiva, y el algoritmo adopta la forma:

$$R^{(0)} = B - A \cdot X^{(0)} \hspace{5mm} \text{solo en la primera iteración}$$

$$ \alpha_k = \dfrac{(R^{(k)})^T \cdot R^{(k)}}{(R^{(k)})^T \cdot A \cdot R^{(k)}} $$

$$X^{(k+1)} = X^{(k)} + \alpha_k \cdot R^{(k)}$$

$$R^{(k+1)} = R^{(k)} - \alpha_k \cdot A \cdot R^{(k)}$$

In [4]:
def resolverDMR(A, B, tol, pasos=True):
    n = np.shape(A)[0]
    X1 = np.zeros(n)
    R1 = np.copy(B)
    den = np.linalg.norm(B,np.inf)
    if (den==0): den = 1    
    iteracion = 0
    dif = 2*tol
    while (dif>tol):
        if (pasos):
            display(Math("\\text{Vamos a realizar la "+str(iteracion+1)+"ª iteración}")) 
            if (iteracion==0):
                display(Math("\\text{Adoptamos como vector inicial } X^{(0)} = "+r"\begin{bmatrix} 0 \\ 0 \\ ... \\ 0 \end{bmatrix}"))            
                display(Math("\\text{En consecuencia } R^{(0)} = B"))    
        X0 = np.copy(X1) 
        R0 = np.copy(R1).reshape(-1)
        AR0 = np.dot(A,R0)        
        alfa = (np.inner(R0,R0) / np.inner(R0,AR0)).item()
        X1 = X0 + alfa*R0       
        R1 = R0 - alfa*AR0    
        dif = np.linalg.norm(R1.transpose(),np.inf)/den       
        if (pasos):
            display(Math("A \\cdot R^{("+str(iteracion)+")} = "+bmatrix(AR0)+"^T"))   
            exp = r"\alpha_"+str(iteracion)+" = \dfrac{(R^{("+str(iteracion)+")})^T \cdot R^{("+str(iteracion)+")}}{(R^{("+str(iteracion)+")})^T \cdot A \cdot R^{("+str(iteracion)+")}} =" +str(alfa)
            display(Math(exp)) 
            exp = "X^{("+str(iteracion+1)+")} = X^{("+str(iteracion)+r")} + \alpha_{"+str(iteracion)+"} \cdot R^{("+str(iteracion)+")} = "+bmatrix(X1)
            display(Math(exp))
            exp = "R^{("+str(iteracion+1)+")} = R^{("+str(iteracion)+r")} - \alpha_{"+str(iteracion)+r"} \cdot A \cdot R^{("+str(iteracion)+")} = "+bmatrix(R1)
            display(Math(exp))            
            exp = "\\text{Evaluamos el criterio corte: } \\frac{|| R^{("+str(iteracion+1)+")}||}{|| B ||} = "+str(dif)            
            if (dif>tol):
                exp += " > tol = "+str(tol)
                display(Math(exp)) 
            else:
                exp +=  " \leq tol = "+str(tol)
                display(Math(exp)) 
                exp = "\\text{Y hemos encontrado nuestra solución aproximada: } X^{("+str(iteracion+1)+")} = "+bmatrix(X1)
                display(Math(exp))
        iteracion += 1                 
    return (X1)

In [5]:
resolverDMR(A,B,10**-4,True)

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

array([ 1.10808236,  2.00644686, -1.53753536,  0.83332234])

### Metodo de los Gradientes Conjugados:

Puesto que la utilización de los residuos como direcciones de búsqueda de la solución termina repitiendo direcciones, este método propone avanzar utilizando direcciones ortogonales a éstos (que se denominarán $d^{(k)}$). 
Para hallar sucesivamente estas direcciones recurre al método de Gram-Schmidt calculando el $\beta$ correspondiente. Este método converge si A es simétrica definida positiva, **lo hace en a lo sumo tantas iteaciones como autovalores distintos tiene $A$ (como mucho n)** y el algoritmo adopta la forma:

$$d^{(0)} = R^{(0)} = B - A \cdot X^{(0)} \hspace{5mm} \text{solo en la primera iteración}$$

$$ \alpha_k = \dfrac{(R^{(k)})^T \cdot R^{(k)}}{(d^{(k)})^T \cdot A \cdot d^{(k)}} $$

$$X^{(k+1)} = X^{(k)} + \alpha_k \cdot d^{(k)}$$

$$R^{(k+1)} = R^{(k)} - \alpha_k \cdot A \cdot d^{(k)}$$

$$ \beta_{k+1} = \dfrac{(R^{(k+1)})^T \cdot R^{(k+1)}}{(R^{(k)})^T \cdot R^{(k)}} $$

$$d^{(k+1)} = R^{(k+1)} + \beta_{k+1} \cdot d^{(k)}$$

In [6]:
def resolverMGC(A, B, tol, pasos=True):
    n = np.shape(A)[0]
    X1 = np.zeros(n)
    R1 = np.copy(B)
    d1 = np.copy(B)
    den = np.linalg.norm(B,np.inf)
    if (den==0): den = 1    
    iteracion = 0
    dif = 2*tol
    while (dif>tol):
        if (pasos):
            display(Math("\\text{Vamos a realizar la "+str(iteracion+1)+"ª iteración}")) 
            if (iteracion==0):
                display(Math("\\text{Adoptamos como vector inicial } X^{(0)} = "+r"\begin{bmatrix} 0 \\ 0 \\ ... \\ 0 \end{bmatrix}"))            
                display(Math("\\text{En consecuencia } d^{(0)} = R^{(0)} = B"))    
        X0 = np.copy(X1) 
        R0 = np.copy(R1).reshape(-1)
        d0 = np.copy(d1).reshape(-1)
        Ad0 = np.dot(A,d0)        
        alfa = (np.inner(R0,R0) / np.inner(d0,Ad0)).item()
        X1 = X0 + alfa*d0       
        R1 = R0 - alfa*Ad0 
        beta = (np.inner(R1,R1) / np.inner(R0,R0)).item()
        d1 = R1 + beta*d0        
        dif = np.linalg.norm(R1.transpose(),np.inf)/den        
        if (pasos):
            display(Math("A \\cdot d^{("+str(iteracion)+")} = "+bmatrix(Ad0)+"^T"))   
            exp = r"\alpha_"+str(iteracion)+" = \dfrac{(R^{("+str(iteracion)+")})^T \cdot R^{("+str(iteracion)+")}}{(d^{("+str(iteracion)+")})^T \cdot A \cdot d^{("+str(iteracion)+")}} =" +str(alfa)
            display(Math(exp)) 
            exp = "X^{("+str(iteracion+1)+")} = X^{("+str(iteracion)+r")} + \alpha_{"+str(iteracion)+"} \cdot d^{("+str(iteracion)+")} = "+bmatrix(X1)
            display(Math(exp))
            exp = "R^{("+str(iteracion+1)+")} = R^{("+str(iteracion)+r")} - \alpha_{"+str(iteracion)+r"} \cdot A \cdot d^{("+str(iteracion)+")} = "+bmatrix(R1)
            display(Math(exp)) 
            exp = r"\beta_{"+str(iteracion+1)+"} = \dfrac{(R^{("+str(iteracion+1)+")})^T \cdot R^{("+str(iteracion+1)+")}}{(R^{("+str(iteracion)+")})^T \cdot R^{("+str(iteracion)+")}} =" +str(beta)
            display(Math(exp))              
            exp = "d^{("+str(iteracion+1)+")} = R^{("+str(iteracion+1)+r")} + \beta_{"+str(iteracion+1)+"} \cdot d^{("+str(iteracion)+")} = "+bmatrix(X1)
            display(Math(exp))            
            exp = "\\text{Evaluamos el criterio corte: } \\frac{|| R^{("+str(iteracion+1)+")}||}{|| B ||} = "+str(dif)            
            if (dif>tol):
                exp += " > tol = "+str(tol)
                display(Math(exp)) 
            else:
                exp +=  " \leq tol = "+str(tol)
                display(Math(exp)) 
                exp = "\\text{Y hemos encontrado nuestra solución aproximada: } X^{("+str(iteracion+1)+")} = "+bmatrix(X1)
                display(Math(exp))    
        iteracion += 1                
    return (X1)

In [7]:
resolverMGC(A,B,10**-4,True)

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

array([ 1.10818455,  2.0063638 , -1.53774085,  0.83348064])