![Curso Schwarz-Sosa-Suriano](http://www.fi.uba.ar/sites/default/files/logo.png)
# Perturbaciones Experimentales
***
**Curso Schwarz - Sosa - Suriano**
- Métodos Numéricos. *Curso 2*
- Análisis Numérico I. *Curso 4*
- Métodos Matemáticos y Numéricos. *Curso 6*

Luego de analizar los procedimientos de propagación de errores inherentes y de redondeo, vimos que la Gráfica de Proceso nos permitía llegar a la siguientes expresión:

$$ e_{total} \leq Cp.r + Te.\mu$$

A pesar de haber contado con una librería que nos permitía despejar Cp y Te a partir de plantear el orden de las las operaciones del algoritmo, debemos tener en cuenta que en el ejercicio de la profesión será muy habitual encontrarnos con alguna de las siguientes situaciones:

- El algoritmo tiene una cantidad de operaciones dificil de volcar a una Gráfica de Proceso.
- No conocemos la expresión matemática ni las instrucciones de un algoritmo.

En estos casos puede resultar interesante estimar los valores de Cp y Te en lugar de buscar sus expresiones exactas

En los desarrollos matemáticos que veremos a continuación consideraremos un algoritmo cuya expresión resumiremos como $f(x)$ -o $f(x_0...x_n)$ con varias variables- del que podemos calcular su resultado numérico aunque no conozcamos su expresión matemática o no podamos desarrollar su gráfica de proceso.

## 1. Estimación de Cp

En un video aclaratorio sobre el requisito $ \frac{Te}{Cp} \not \gg 1 $ (que debe cumplirse para que un algoritmo sea estable) que en la mayor parte de las aplicaciones de Ingeniería nos encontraremos con que la cota $r$ será en general mucho mayor a la cota $\mu$.


En ese contexto, y con el objetivo de estimar el valor de $Cp$, vamos a considerar despreciable el término relacionado con el error de redondeo en la expresión de la cota del error total. La validez de esta simplificación la mediremos en términos del éxito que tengamos a la hora de estimar el valor de $Cp$:

$$ e_{total} \leq Cp.r$$

La propuesta para estimar $Cp$ surge de introducir una leve modificación a esta desigualdad:

$$ \frac{e_{total}}{r} \leq Cp$$ 

Recordemos que:
$$ e_{total} = \left | \frac{f(\hat x)-f(x)}{f(x)} \right | \hspace{5mm} con \hspace{5mm}\hat x = x . (1+i_x)$$

Esta vez, en lugar de pensar en un $i_x$ desconocido acotado por un valor $r$, vamos directamente a proponer una **perturbación experimental** $r$ que nos permitirá decir que:

$$ \hat x = x . (1\pm r) \hspace{5mm} \Rightarrow \hspace{5mm} e_{total} =  \left | \frac{f [x . (1 \pm r)]-f(x)}{f(x)} \right | $$ 

Y como en verdad ya no pretendemos buscar el valor exacto de una cota del error sino una estimación para $Cp$:

$$ \frac{e_{total}}{r} \leq Cp \hspace{5mm} \Rightarrow \hspace{5mm}  Cp \geq  \frac{e_{total}}{r}  \hspace{5mm} \Rightarrow \hspace{5mm} Cp \approx e_{total}.\frac{1}{r}$$

De lo que resulta:
$$ Cp \approx \left |\frac{f[x.(1 \pm r)]-f(x)}{f(x)} \right |. \frac{1}{r} $$

En consecuencia, lo que haremos para estimar el valor de Cp será:

1. Definir un valor de $x$ y una *perturbación experimental* $r$

2. Calcular con nuestro algoritmo $f(x)$, $f[x.(1 + r)]$ y $f[x.(1-r)]$

3. Obtener:

    $$Cp^{(+)} = \left |\frac{f[x.(1 + r)]-f(x)}{f(x)} \right |. \frac{1}{r}$$
    
    $$Cp^{(-)} = \left |\frac{f[x.(1 - r)]-f(x)}{f(x)} \right |. \frac{1}{r}$$

4. Adoptar como estimación de $Cp$:
    $$Cp \approx máx  \begin{Bmatrix} Cp^{(+)} \\ Cp^{(-)}  \end{Bmatrix} $$

Cuando tengamos un algoritmo con varias variables de entrada $f(x_0,x_1,...,x_n)$ utilizaremos un único valor de *perturbación experimental* $r$ para todas ellas, y perturbando de a una variable por vez hallaremos:

$$Cp_{x_j} = máx  \begin{Bmatrix} Cp^{(+)}_{x_j} \\ Cp^{(-)}_{x_j}  \end{Bmatrix} \hspace{5mm} con \hspace{5mm} j = 0, 1, ..., n$$

Y una vez que hayamos estimado *esa especie de* $Cp$ para cada variable, haremos:

$$Cp \approx  \sum_{j=0}^{n} Cp_{x_j} $$ 

Análogamente a lo que hacíamos con la expresión teórica de $Cp$ para varias variables:

$$
Cp = \sum_{j=0}^{n}
\left|\frac{\frac{\partial f(x_0...x_n)}{\partial x_j}.x_j}{f(x_0...x_n)}\right| 
$$ 

## 1. Estimación de Te

Volvamos a nuestra expresión del error total:
$$ e_{total} \leq Cp.r + Te.\mu$$

Imaginemos que tenemos a nuestra disposición un mismo algoritmo, que puede correrse en dos ordenadores distintos, cada uno de los cuales tiene una cantidad distinta de dígitos en su sistema de representación:

**Ordenador 1:**
- Sistema de representación con $t$ dígitos
- Cota del error de redondeo: $\mu_t = 0,5 . 10^{1-t}$
- $ e_t \leq Cp.r + Te.\mu_t$

**Ordenador 2:**
- Sistema de representación con $s$ dígitos
- Cota del error de redondeo: $\mu_s = 0,5 . 10^{1-s}$    
- $ e_s \leq Cp.r + Te.\mu_s$

Si restamos las dos expresiones de error total:

$$ e_t - e_s \leq (Cp.r + Te.\mu_t) - (Cp.r + Te.\mu_s) $$

$$ e_t - e_s \leq Cp.r - Cp.r + Te.\mu_t - Te.\mu_s $$

$$ e_t - e_s \leq Te.\mu_t - Te.\mu_s$$

$$ e_t - e_s \leq Te.(\mu_t - \mu_s)$$

$$ Te  \geq (e_t - e_s).\frac{1}{\mu_t - \mu_s}$$

Nuevamente, como lo que buscamos es encontrar una estimación de $Te$ vamos a transformar la desigualdad en una aproximación:

$$ Te  \approx (e_t - e_s).\frac{1}{\mu_t - \mu_s}$$

Sabemos además que:

$$ e_t = \frac{f(x_0...x_n)_t -  f(x_0...x_n)}{ f(x_0...x_n)}$$

$$ e_s = \frac{f(x_0...x_n)_s -  f(x_0...x_n)}{ f(x_0...x_n)}$$

Con lo cual:

$$ Te  \approx (\frac{f(x_0...x_n)_t -  f(x_0...x_n)}{ f(x_0...x_n)} - \frac{f(x_0...x_n)_s -  f(x_0...x_n)}{ f(x_0...x_n)}).\frac{1}{\mu_t - \mu_s}$$

$$ Te  \approx (\frac{f(x_0...x_n)_t -  f(x_0...x_n)}{ f(x_0...x_n)} - \frac{f(x_0...x_n)_s -  f(x_0...x_n)}{ f(x_0...x_n)}).\frac{1}{\mu_t - \mu_s}$$

$$ Te  \approx \frac{f(x_0...x_n)_t - f(x_0...x_n)_s}{ f(x_0...x_n)}.\frac{1}{\mu_t - \mu_s}$$

De esta última expresión conocemos $\mu_t$ y $\mu_s$ y con tan solo correr nuestro algoritmo en cada ordenador podríamos hallar $f(x_0...x_n)_t$ y $f(x_0...x_n)_s$

Para poder estimar $Te$ lo único que nos estaría faltando conocer $f(x_0...x_n)$, pero en tren de buscar una estimación y no un valor exacto, bien podemos asumir:

$$Asumiendo \hspace{5mm} t>s \hspace{5mm} \Rightarrow \hspace{5mm} f(x_0...x_n) \approx f(x_0...x_n)_t$$

$$ Te  \approx \frac{f(x_0...x_n)_t - f(x_0...x_n)_s}{ f(x_0...x_n)_t}.\frac{1}{\mu_t - \mu_s}$$

$$ Te  \approx \frac{f(x_0...x_n)_t - f(x_0...x_n)_s}{ f(x_0...x_n)_t}.\frac{1}{\mu_t - \mu_s}$$

Con esta última expresión, para poder estimar $Te$ deberíamos:

1. Definir un valor para $x_0, x_1,..., x_n$

2. Hacer correr el algoritmo con $t$ dígitos y con $s$ dígitos **en cada operación intermedia** y hallar:
    - $ f(x_0...x_n)_t $
    - $ f(x_0...x_n)_s $

3. Estimar $Te$

In [1]:
%matplotlib inline
from graficasdeproceso import *
import sympy as sm
import numpy as np

## 3. Ejemplo de estimación de Cp

Vamos a a plantear el problema $f(x_0,x_1,x_2) = x_0.x_1-x_2$:

In [2]:
operaciones = ['x0*x1','op0-x2']
algoritmo = GraficaDeProceso(['x0','x1','x2'], operaciones)
algoritmo.ErrorRedondeo(0)
algoritmo.ErrorInherente(0)

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [3]:
algoritmo.mostrar(10)

interactive(children=(IntSlider(value=10, description='width', max=30, min=-10), IntSlider(value=10, descripti…

In [4]:
algoritmo.CotaErrorTotal()

<IPython.core.display.Math object>

In [5]:
algoritmo.Cp(1)

<IPython.core.display.Math object>

In [6]:
# Asumimos valores de x,y,z para calcular el Cp exacto con esa fórmula
X = np.array([2,2.00002,4.0001])
cpTeorico = algoritmo.funcionCp(X[0],X[1],X[2])
cpTeorico

200003.0000016504

Ahora vamos a estimar Cp siguiendo el proceso visto al comienzo de este video:

In [7]:
def Funcion(x,y,z):
    return x*y-z
r = 0.05
f = Funcion (X[0],X[1],X[2])
f

-5.9999999999504894e-05

Vamos a estimar $Cp_{x_j}^{(+)}$ y $Cp_{x_j}^{(-)}$ para cada variable:

In [8]:
cpPos = np.zeros(3)
cpNeg = np.zeros(3)

In [19]:
cpPos[0] = np.abs(((Funcion(X[0]*(1+r),X[1],X[2]) - f) / f) * (1/r))
cpNeg[0] = np.abs(((Funcion(X[0]*(1-r),X[1],X[2]) - f) / f) * (1/r))

In [10]:
cpPos[1] = np.abs(((Funcion(X[0],X[1]*(1+r),X[2]) - f) / f) * (1/r))
cpNeg[1] = np.abs(((Funcion(X[0],X[1]*(1-r),X[2]) - f) / f) * (1/r))

In [11]:
cpPos[2] = np.abs(((Funcion(X[0],X[1],X[2]*(1+r)) - f) / f) * (1/r))
cpNeg[2] = np.abs(((Funcion(X[0],X[1],X[2]*(1-r)) - f) / f) * (1/r))

In [12]:
cpPos 

array([66667.33333388, 66667.33333388, 66668.33333388])

In [13]:
cpNeg

array([66667.33333388, 66667.33333388, 66668.33333388])

Ahora vamos a buscar el máximo entre $Cp_{x_j}^{(+)}$ y $Cp_{x_j}^{(-)}$ para cada variable:

In [14]:
cpMax = np.zeros(3)
for i in range(3):
    cpMax[i] = np.amax([cpPos[i],cpNeg[i]])
cpMax 

array([66667.33333388, 66667.33333388, 66668.33333388])

Y por último, debemos sumar los $Cp_{x_j}$ para hallar el $Cp$:

In [20]:
cpEstimado = 0
for i in range(3):
    cpEstimado += cpMax[i]

In [16]:
cpEstimado

200003.00000165068

In [17]:
cpTeorico

200003.0000016504

Como vemos, la estimación es bastante cercana al cálculo teórico.